spring:
  data:
    mongodb:
      username: mongodb
      password: mongodb
      host: localhost
      port: 27019
      database: customer
      authentication-database: admin
server:
  port: 8090
