spring:
  data:
    mongodb:
      username: mongodb
      password: mongodb
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:org.bibek.kafka.OrderConfirmation, paymentConfirmation:com.bibek.ecommerce.payment.notification

  mail:
    host: localhost
    port: 1025
    username: bibek
    password: bibek
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

server:
  port: 8040